# bessere Scroll-History
set -g history-limit 100000

# Mausunterstützung
set -g mouse on

# bessere Farben
set -g default-terminal "screen-256color"

# schneller Pane-Wechsel
setw -g mode-keys vi

# Statusbar etwas aufräumen
set -g status-bg colour235
set -g status-fg white
