[Interface]
PrivateKey = <ENTER_PRIVATE_KEY_HERE>
Address = <ENTER_IP_ADDRESS_HERE>
MTU=1340

[Peer]
PublicKey = WLKQE4naMWM01M1tx6AQ/vL+a8VVS40jtG/SpqKDKG0=
AllowedIPs = 10.7.0.0/16
Endpoint = 132.231.59.246:51820
