[Interface]
PrivateKey = 8ObJeDxDq8ie1seIi1hNWyjbcUFs8FnXrguswLCXOUc=
Address = 10.7.14.35/16
MTU=1340

[Peer]
PublicKey = WLKQE4naMWM01M1tx6AQ/vL+a8VVS40jtG/SpqKDKG0=
AllowedIPs = 10.7.0.0/16
Endpoint = 132.231.59.246:51820
