[Interface]
PrivateKey = <ENTER_PRIVATE_KEY_HERE>
Address = <ENTER_IP_ADDRESS_HERE>

[Peer]
PublicKey = <REMOVED-PEER-KEY>=
AllowedIPs = <REMOVED-IP>, <REMOVED-NET>, <REMOVED-IP>, <REMOVED-IP>
Endpoint = <REMOVED-IP>
PersistentKeepalive = 25
